mixin:
  dns: #减少dns污染
    enable: true
    enhanced-mode: fake-ip #延迟更低
    nameserver: #尽量别用外国的DNS，让代理端处理代理域名
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    fallback: #有污染的情况下使用
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4 # 该IP段基本是已经被污染的ip端
      domain:
        - '+.google.com'
        - '+.youtube.com' 
    fake-ip-filter: #让微软系和一些stun走直连
      - +.stun.*.*
      - +.stun.*.*.*
      - +.stun.*.*.*.*
      - +.stun.*.*.*.*.*
      - localhost.ptlogin2.qq.com
      - "*.n.n.srv.nintendo.net"
      - +.stun.playstation.net
      - xbox.*.*.microsoft.com
      - "*.*.xboxlive.com"
      - "*.msftncsi.com"
      - "*.msftconnecttest.com"
      - WORKGROUP
  tun: #实现全局代理
    enable: true
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - any:53
      - tcp://any:53
